# Generated by Django 3.1 on 2021-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210117_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
